# Generated by Django 5.0.6 on 2024-06-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('progress', models.IntegerField(default=0)),
                ('transcribed_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
